using System;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Text.Json;
using System.Threading.Tasks;
using Kallots.Core.Interfaces;
using Microsoft.Extensions.Configuration;

namespace Kallots.Worker.Services
{
    public class GroqLlmProvider : ILlmProvider
    {
        private readonly HttpClient _httpClient;
        private readonly string _apiKey;
        private const string GroqEndpoint = "https://api.groq.com/openai/v1/chat/completions";

        // Dependency Injection: .NET automatically provides HttpClient and IConfiguration
        public GroqLlmProvider(HttpClient httpClient, IConfiguration configuration)
        {
            _httpClient = httpClient;
            
            // Reads the API key safely from environment variables or appsettings.json
            _apiKey = configuration["GroqApiKey"] ?? throw new ArgumentNullException("GroqApiKey is missing in configuration.");
        }

        public async Task<string> ProcessIntentAsync(string userText)
        {
            // System Prompt designed strictly for intent extraction (MVP scope)
            var systemPrompt = "You are Kallots, a Windows Desktop Assistant. " +
                               "Analyze the user's input and return ONLY a machine-readable intent command. " +
                               "Do not include any conversational text or formatting. " +
                               "Examples: If user says 'abre o vs code', return 'OPEN_VSCODE'. " +
                               "If user says 'abre o navegador', return 'OPEN_BROWSER'.";

            // Creating an anonymous object to represent the Groq API payload
            var requestBody = new
            {
                model = "llama3-70b-8192", // Ultra-fast LLaMA model on Groq
                messages = new[]
                {
                    new { role = "system", content = systemPrompt },
                    new { role = "user", content = userText }
                },
                temperature = 0.1 // Low temperature to ensure robotic, predictable output
            };

            // Serialize the C# object into a JSON string
            var jsonContent = new StringContent(JsonSerializer.Serialize(requestBody), Encoding.UTF8, "application/json");

            // Attach the API Key to the request headers
            _httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", _apiKey);

            // Send the HTTP POST request to Groq
            var response = await _httpClient.PostAsync(GroqEndpoint, jsonContent);
            response.EnsureSuccessStatusCode(); // Throws an exception if the API returns an error

            // Read the JSON response
            var responseString = await response.Content.ReadAsStringAsync();
            
            // Parse the JSON to extract exactly the text generated by the LLM
            using var jsonDocument = JsonDocument.Parse(responseString);
            var intent = jsonDocument.RootElement
                .GetProperty("choices")[0]
                .GetProperty("message")
                .GetProperty("content")
                .GetString();

            return intent?.Trim() ?? "UNKNOWN_COMMAND";
        }
    }
}
